#Template Pipeline for CI/CD
# trigger:
# - main

resources:
  repositories:
    - repository: self
      trigger: none

stages:
  - stage: Build
    displayName: Build .Net Core Solution
    jobs:
      - job: Build
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: DotNetCoreCLI@2
            displayName: Restore
            inputs:
              command: "restore"
              projects: "**/*.sln"
              feedsToUse: "select"

          - task: DotNetCoreCLI@2
            displayName: Build
            inputs:
              command: "build"
              projects: "**/*.sln"

          - task: DotNetCoreCLI@2
            displayName: Publish
            inputs:
              command: "publish"
              publishWebProjects: true
              arguments: "-o $(Build.ArtifactStagingDirectory)"

          - task: PublishBuildArtifacts@1
            displayName: Publish Artifacts ADO - Website
            inputs:
              pathToPublish: "$(Build.ArtifactStagingDirectory)"
              artifactName: Website

  - stage: Deploy
    displayName: Deploy to an Azure Web App
    jobs:
      - job: Deploy
        pool:
          vmImage: "windows-2019"
        steps:
          - task: DownloadBuildArtifacts@1
            inputs:
              buildType: "current"
              downloadType: "single"
              artifactName: "Website"
              downloadPath: "$(Build.ArtifactStagingDirectory)"

          - task: AzureRmWebAppDeployment@5
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: 'Azure サブスクリプション 1(fa9bad56-093e-485a-86f9-ca7b251fdf10)'
              appType: 'webApp'
              WebAppName: 'az400eshoponweb2324122070'
              packageForLinux: '$(Build.ArtifactStagingDirectory)/**/Web.zip'
              AppSettings: '-UseOnlyInMemoryDatabase true -ASPNETCORE_ENVIRONMENT Development'