#NAME THE PIPELINE SAME AS FILE (WITHOUT ".yml")

# Trigger CD when CI executed succesfully
resources:
  pipelines:
    - pipeline: eshoponweb-ci
      source: eshoponweb-ci # given pipeline name
      trigger: true


variables:
  resource-group: 'rg-az400-test'
  location: 'japanwest'
  templateFile: 'webapp.bicep'
  subscriptionid: 'fa9bad56-093e-485a-86f9-ca7b251fdf10'
  azureserviceconnection: 'azure subs'
  webappname: 'az400-webapp-20251211'
  # webappname: 'webapp-windows-eshop'
  

stages:
- stage: Deploy
  displayName: Deploy to WebApp
  jobs:
  - job: Deploy
    pool:
      vmImage: windows-latest
    steps:
    #download artifacts
    - download: eshoponweb-ci
  
    # Deploy App Service Plan + App Service using Bicep
    - task: AzureResourceManagerTemplateDeployment@3
      displayName: Deploy App Service Plan Bicep
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: '$(azureserviceconnection)'
        subscriptionId: '$(subscriptionid)'
        action: 'Create Or Update Resource Group'
        resourceGroupName: '$(resource-group)'
        location: '$(location)'
        templateLocation: 'Linked artifact'
        csmFile: '$(Pipeline.Workspace)/eshoponweb-ci/Bicep/$(templateFile)'
        overrideParameters: '-webAppName $(webappname) -location $(location)'
        deploymentMode: 'Incremental'
        deploymentOutputs: 'asp-json'
    
    #Publish Website to Azure WebApp
    - task: AzureRmWebAppDeployment@4
      displayName: Publish Website to WebApp
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: '$(azureserviceconnection)'
        appType: 'webApp'
        WebAppName: '$(webappname)'
        packageForLinux: '$(Pipeline.Workspace)/eshoponweb-ci/Website/Web.zip'
      

    
